# Generated by Django 3.1.1 on 2021-03-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='problem_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='area_problem_selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.area_available')),
                ('problem_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.problem_available')),
            ],
        ),
    ]
