# Generated by Django 3.1.1 on 2021-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_problem_selection',
            name='area_selection',
            field=models.TextField(),
        ),
    ]
