# Generated by Django 3.1.1 on 2021-03-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20210315_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_problem_selection',
            name='problem_selection',
            field=models.TextField(),
        ),
    ]
