# Generated by Django 3.1.1 on 2021-03-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_auto_20210315_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_problem_selection',
            name='area_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.area_available'),
        ),
        migrations.AlterField(
            model_name='area_problem_selection',
            name='problem_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.problem_available'),
        ),
    ]
