# Generated by Django 3.1.7 on 2021-03-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.TextField()),
                ('area', models.CharField(max_length=110)),
                ('pincode', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='img')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.problem')),
            ],
        ),
    ]
