# Generated by Django 3.1.7 on 2021-03-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='latlong',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
