# Generated by Django 3.1.1 on 2020-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20200929_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pincode',
            field=models.CharField(max_length=8),
        ),
    ]
