# Generated by Django 3.1.7 on 2021-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
