# Generated by Django 3.1.7 on 2021-03-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='status_list',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status_type')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_id', models.IntegerField()),
                ('desc', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status_type')),
            ],
        ),
    ]
